schemaVersion: "2.0.0"

# Metadata
metadataTest:
  labels:
    - key: "maintainer"
      value: "Emmanuel braux <emmanuel.braux@example.com>"
    - key: "description"
      value: "Docker Image for ocean4dvarnet"
    - key: "version"
      value: "1.0"
    - key: "org.opencontainers.image.authors"
      value: "Emmanuel braux"
    - key: "org.opencontainers.image.documentation"
      value: "https://cia-oceanix.github.io/ocean4dvarnet/"
  exposedPorts: []
  #entrypoint: ["/bin/bash", "-c", "source /opt/conda/etc/profile.d/conda.sh && conda activate oceanenv && exec \"$@\"", "--"]
  user: "1000"

# File existence tests
fileExistenceTests:
  - name: "Miniconda installation"
    path: "/home/ocean4dvarnet/mamba/bin/conda"
    shouldExist: true
    permissions: "-rwxr-xr-x"
  - name: "Mamba installation"
    path: "/home/ocean4dvarnet/mamba/bin/mamba"
    shouldExist: true
    permissions: "-rwxr-xr-x"
  - name: "Environment Init file"
    path: "/home/ocean4dvarnet/mamba/init.sh"
    shouldExist: true
    permissions: "-rw-r--r--"
  - name: "Environment configuration"
    path: "/home/ocean4dvarnet/.bashrc"
    shouldExist: true
    permissions: "-rw-r--r--"
  - name: "Workspace directory"
    path: "/home/ocean4dvarnet/work"
    shouldExist: true
    permissions: "drwxr-xr-x"

# File content tests
fileContentTests:
  - name: "Check .bashrc content"
    path: "/home/ocean4dvarnet/.bashrc"
    expectedContents: ["source /home/ocean4dvarnet/mamba/init.sh"]
  - name: "Check LC_ALL environment variable"
    path: "/etc/environment"
    expectedContents: ["LC_ALL=en_US.UTF-8"]
  - name: "Check LANG environment variable"
    path: "/etc/environment"
    expectedContents: ["LANG=en_US.UTF-8"]

# Command tests
commandTests:
  - name: "Check conda version"
    command: "/home/ocean4dvarnet/mamba/bin/conda"
    args: ["--version"]
    expectedOutput: ["conda 25.3.*"]
  - name: "Check mamba version"
    command: "/home/ocean4dvarnet/mamba/bin/mamba"
    args: ["--version"]
    expectedOutput: ["2.1.*"]
  - name: "Check Python version"
    command: "/home/ocean4dvarnet/mamba/bin/python"
    args: ["--version"]
    expectedOutput: ["Python 3.12.*"]
