name: Container Structure Test
description: Use Google's Container Structure Test to test a Docker image
# From https://github.com/InseeFrLab/images-datascience/blob/main/.github/actions/container-structure-test/action.yml

inputs:
  image:
    description: Image name
    required: true
  config:
    description: Configuration file for the tests
    required: true

runs:
  using: composite
  steps:
    - name: Download Container Structure Test
      shell: bash
      run: |
        curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
        chmod +x container-structure-test-linux-amd64
        sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
    - name: Test container
      shell: bash
      run: |
        container-structure-test test --image ${{ inputs.image }} --config ${{ inputs.config }}
