name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - ci/create-docker-image # Trigger on push to the ci/create-docker-image branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1


    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

        
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: docker/cuda12.6.1-u22
        push: false
        tags: ghcr.io/${{ github.repository_owner }}/ocean4dvarnet-env:cuda12.6.1-u22

    - name: Test image using Google's Container Structure Test
      uses: ./.github/actions/container-structure-test
      with:
        image: ghcr.io/${{ github.repository_owner }}/ocean4dvarnet-env:cuda12.6.1-u22
        config: docker/cuda12.6.1-u22/tests.yaml

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
      context: docker/cuda12.6.1-u22
      push: true
      tags: ghcr.io/${{ github.repository_owner }}/ocean4dvarnet-env:cuda12.6.1-u22
